plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

branches:
  - name: +([0-9])?(.{+([0-9]),x}).x
  - name: main
    prerelease: 'beta'
    channel: beta
  - name: next
    prerelease: true
  - name: pre/rc
    prerelease: '${name.replace(/^pre\\//g, "")}'
