plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

branches:
  - name: v+([0-9])?(.{+([0-9]),x}).x
  - name: main
  - name: next
    prerelease: true
